version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017/financial_intelligence
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY:-default_api_key_change_me}
      - EMBEDDING_MODEL=ProsusAI/finbert
      - USE_EXAMPLE_TEXT=true
    volumes:
      - ./logs:/app/logs
      - ./temp_files:/app/temp_files
      - ./faiss_index:/app/faiss_index
      - ./example_financial_text.txt:/app/example_financial_text.txt
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: